import type { CreateUiContentInput } from './ui-content.types';

type UiContentDefault = CreateUiContentInput & { enabled: boolean };

function item(
  key: string,
  group: string,
  label: string,
  value: string,
): UiContentDefault {
  return { key, group, label, value, enabled: true };
}

export const UI_CONTENT_DEFAULTS: UiContentDefault[] = [
  item('brand.name', 'brand', '品牌名称', '芯茂微'),
  item('brand.platform', 'brand', '平台英文名称', 'XM-SolutionHub'),
  item('brand.suffix', 'brand', '品牌后缀', 'SolutionHub'),
  item('common.active', 'common', '上架状态', '已上架'),
  item('common.retry', 'common', '重试按钮', '重试'),
  item('common.notFound', 'common', '页面不存在', '页面不存在'),
  item('common.pageError', 'common', '页面错误标题', '页面发生错误'),
  item('common.unknownError', 'common', '未知错误', '未知错误'),
  item('common.yes', 'common', '布尔值：是', '是'),
  item('common.no', 'common', '布尔值：否', '否'),
  item('common.loading', 'common', '加载中', '加载中...'),

  item('main.nav.home', 'main', '导航：首页', '首页'),
  item('main.nav.selection', 'main', '导航：选型', '选型'),
  item('main.nav.solutions', 'main', '导航：方案资料', '方案资料'),
  item('main.nav.ai', 'main', '导航：AI 问答', 'AI问答'),
  item('main.nav.profile', 'main', '导航：我的', '我的'),
  item('main.cta.chat', 'main', '开始对话按钮', '开始对话'),
  item('main.footer.description', 'main', '页脚说明', '专业的电源芯片选型与方案资料平台，毫秒级匹配、可解释推荐、全规格书可预览。'),
  item('main.footer.selection', 'main', '页脚：智能选型', '智能选型'),
  item('main.footer.ai', 'main', '页脚：AI 技术问答', 'AI 技术问答'),

  item('auth.login', 'auth', '登录按钮', '登录'),
  item('auth.register', 'auth', '注册按钮', '注册'),

  item('home.hero.title', 'home', '首页主标题', '芯茂微智能选型平台'),
  item('home.hero.subtitle', 'home', '首页主说明', '输入电气参数即可匹配可解释型号，联动规格书、方案资料与 AI 技术问答，减少工程师在资料表之间反复查找的时间。'),
  item('home.quick.title', 'home', '快速选型标题', '快速选型'),
  item('home.quick.hint', 'home', '快速选型说明', '核心电气参数必填，应用与认证可选'),
  item('home.quick.submit', 'home', '快速选型按钮', '开始选型'),
  item('home.solutions.title', 'home', '热门方案标题', '热门应用方案'),
  item('home.solutions.view', 'home', '查看方案按钮', '查看方案资料'),
  item('home.solutions.empty', 'home', '热门方案空态', '暂无已上架方案'),
  item('home.products.title', 'home', '推荐型号标题', '推荐型号'),
  item('home.products.enterSelection', 'home', '完整选型入口', '进入完整选型'),
  item('home.products.empty', 'home', '推荐型号空态', '暂无推荐型号'),
  item('home.ai.title', 'home', 'AI 模块标题', 'AI 技术问答'),
  item('home.ai.subtitle', 'home', 'AI 模块说明', '用自然语言描述需求，系统会基于资料库返回带来源的回答，方便追溯到规格书页码和方案片段。'),

  item('solutions.title', 'solutions', '方案列表标题', '方案资料'),
  item('solutions.subtitle', 'solutions', '方案列表说明', '按应用方案查看关联型号、测试报告与设计资料'),
  item('solutions.search.placeholder', 'solutions', '方案搜索占位', '搜索方案名称或应用场景'),
  item('solutions.error', 'solutions', '方案加载失败', '方案加载失败'),
  item('solutions.empty', 'solutions', '方案列表空态', '暂无已上架方案'),
  item('solutions.card.view', 'solutions', '方案卡片查看按钮', '查看方案与资料'),
  item('solution.detail.notFound', 'solutions', '方案详情不存在', '方案未找到'),
  item('solution.detail.backSelection', 'solutions', '返回选型按钮', '返回选型'),
  item('solution.material.catalog', 'solutions', '资料目录标题', '资料目录'),
  item('solution.material.empty', 'solutions', '资料空态', '资料整理中'),
  item('solution.material.previewTag', 'solutions', '匿名预览标签', '前3页'),
  item('solution.material.loadFailed', 'solutions', '资料加载失败', '资料加载失败'),
  item('solution.tabs.materials', 'solutions', '资料 Tab', '资料'),
  item('solution.tabs.preview', 'solutions', '预览 Tab', '预览'),
  item('solution.tabs.products', 'solutions', '关联型号 Tab', '关联型号'),
  item('solution.products.empty', 'solutions', '关联型号空态', '暂无关联型号'),
  item('solution.preview.empty', 'solutions', '未选择资料提示', '请选择资料'),
  item('solution.preview.error', 'solutions', '预览失败标题', '预览加载失败'),
  item('solution.preview.retry', 'solutions', '预览重试按钮', '重试'),
  item('solution.preview.limited', 'solutions', '匿名预览提示', '当前显示前 {pages} 页预览，登录后查看完整资料'),
  item('solution.preview.unlock', 'solutions', '登录查看完整资料按钮', '登录/注册查看完整资料'),

  item('product.backSelection', 'products', '产品返回选型', '返回选型'),
  item('product.notFound', 'products', '产品不存在', '产品未找到'),
  item('product.loadFailed', 'products', '产品加载失败', '加载失败'),
  item('product.inactive', 'products', '产品下架提示', '产品已下架'),
  item('product.material.complete', 'products', '资料完整标签', '资料完整'),
  item('product.material.preparing', 'products', '资料整理中标签', '资料整理中'),
  item('product.params.title', 'products', '关键参数标题', '关键参数'),
  item('product.applications.title', 'products', '推荐应用标题', '推荐应用'),
  item('product.advantages.title', 'products', '产品优势标题', '产品优势'),
  item('product.datasheet.title', 'products', '产品规格书标题', '规格书'),
  item('product.datasheet.previewable', 'products', '规格书可预览标签', '可预览'),
  item('product.datasheet.view', 'products', '查看规格书按钮', '查看规格书'),
  item('product.solutions.title', 'products', '关联方案标题', '关联方案'),

  item('main.nav.aiShort', 'main', '移动导航 AI', 'AI'),
  item('main.profile', 'main', '个人中心', '个人中心'),
  item('main.admin', 'main', '进入后台', '进入后台'),
  item('main.menu.open', 'main', '打开菜单无障碍文案', '打开菜单'),
  item('main.menu.title', 'main', '移动菜单标题', '导航'),
  item('main.footer.links', 'main', '页脚快速链接标题', '快速链接'),
  item('main.footer.contact', 'main', '页脚联系我们标题', '联系我们'),
  item('main.footer.email', 'main', '联系邮箱', '邮箱：info@xinmaowei.com'),
  item('main.footer.phone', 'main', '联系电话', '电话：400-xxx-xxxx'),
  item('main.footer.copyright', 'main', '版权文案', '芯茂微电子. All rights reserved.'),
  item('main.footer.privacy', 'main', '隐私政策', '隐私政策'),
  item('main.footer.terms', 'main', '服务条款', '服务条款'),

  item('auth.logout', 'auth', '退出登录', '退出登录'),
  item('auth.logout.success', 'auth', '退出成功提示', '已退出登录'),
  item('auth.backHome', 'auth', '返回首页', '返回首页'),
  item('auth.field.email', 'auth', '邮箱字段', '邮箱'),
  item('auth.field.password', 'auth', '密码字段', '密码'),
  item('auth.field.password.placeholder', 'auth', '密码占位文案', '请输入密码'),
  item('auth.field.confirmPassword', 'auth', '确认密码字段', '确认密码'),
  item('auth.field.confirmPassword.placeholder', 'auth', '确认密码占位文案', '再次输入密码'),
  item('auth.login.kicker', 'auth', '登录页眉', 'ACCOUNT ACCESS'),
  item('auth.login.heroTitle', 'auth', '登录页主标题', '登录芯茂微资料与选型工作台'),
  item('auth.login.heroSubtitle', 'auth', '登录页说明', '登录后可继续使用 AI 技术问答、查看完整资料权限，并保留选型与线索上下文。'),
  item('auth.login.security', 'auth', '登录安全说明', 'Refresh Token 使用 HttpOnly Cookie 轮换保护'),
  item('auth.login.subtitle', 'auth', '登录表单说明', '使用您的账户继续'),
  item('auth.login.success', 'auth', '登录成功提示', '登录成功'),
  item('auth.login.failed', 'auth', '登录失败提示', '登录失败，请重试'),
  item('auth.login.noAccount', 'auth', '无账户提示', '还没有账户？'),
  item('auth.login.registerNow', 'auth', '立即注册', '立即注册'),
  item('auth.register.kicker', 'auth', '注册页眉', 'CREATE ACCOUNT'),
  item('auth.register.heroTitle', 'auth', '注册页主标题', '注册后查看完整方案资料'),
  item('auth.register.heroSubtitle', 'auth', '注册页说明', '账户用于资料预览、下载审计、AI 问答与线索跟进，敏感令牌通过服务端 Cookie 策略保护。'),
  item('auth.register.privacyHint', 'auth', '注册隐私说明', '注册即记录隐私版本和同意时间'),
  item('auth.register.subtitle', 'auth', '注册表单说明', '创建新账户解锁完整资料下载与 AI 问答'),
  item('auth.register.success', 'auth', '注册成功提示', '注册成功'),
  item('auth.register.failed', 'auth', '注册失败提示', '注册失败，请重试'),
  item('auth.register.hasAccount', 'auth', '已有账户提示', '已有账户？'),
  item('auth.register.loginNow', 'auth', '立即登录', '立即登录'),
  item('auth.password.length', 'auth', '密码长度要求', '至少 8 个字符'),
  item('auth.password.uppercase', 'auth', '密码大写要求', '大写字母'),
  item('auth.password.lowercase', 'auth', '密码小写要求', '小写字母'),
  item('auth.password.number', 'auth', '密码数字要求', '数字'),
  item('auth.privacy.accept', 'auth', '同意隐私政策', '我已阅读并同意《隐私政策》'),
  item('auth.validation.email', 'auth', '邮箱校验提示', '请输入有效的邮箱地址'),
  item('auth.validation.passwordLength', 'auth', '密码长度校验提示', '密码至少 8 个字符'),
  item('auth.validation.uppercase', 'auth', '密码大写校验提示', '需包含至少 1 个大写字母'),
  item('auth.validation.lowercase', 'auth', '密码小写校验提示', '需包含至少 1 个小写字母'),
  item('auth.validation.number', 'auth', '密码数字校验提示', '需包含至少 1 个数字'),
  item('auth.validation.privacy', 'auth', '隐私政策校验提示', '请阅读并同意隐私政策'),
  item('auth.validation.confirmPassword', 'auth', '确认密码校验提示', '两次输入的密码不一致'),
  item('auth.unlock.title', 'auth', '资料解锁标题', '登录或注册后查看完整资料'),
  item('auth.unlock.subtitle', 'auth', '资料解锁说明', '未登录可预览前 3 页；登录后可查看完整测试报告并下载全部方案资料。'),
  item('auth.unlock.later', 'auth', '继续匿名预览', '继续预览'),

  item('home.metric.match.title', 'home', '首页匹配指标标题', '毫秒级匹配'),
  item('home.metric.match.subtitle', 'home', '首页匹配指标说明', '电压、电流、认证联动评分'),
  item('home.metric.trace.title', 'home', '首页追溯指标标题', '资料可追溯'),
  item('home.metric.trace.subtitle', 'home', '首页追溯指标说明', '型号、方案、PDF 统一入口'),
  item('home.metric.ai.title', 'home', '首页 AI 指标标题', 'AI 有来源'),
  item('home.metric.ai.subtitle', 'home', '首页 AI 指标说明', '基于知识库证据回答'),
  item('home.solutions.kicker', 'home', '热门方案页眉', 'APPLICATIONS'),
  item('home.products.kicker', 'home', '推荐型号页眉', 'RECOMMENDED MODELS'),
  item('home.ai.kicker', 'home', 'AI 模块页眉', 'AI ASSISTANT'),

  item('selection.field.inputVoltageMin', 'selection', '输入电压下限', '输入电压下限'),
  item('selection.field.inputVoltageMax', 'selection', '输入电压上限', '输入电压上限'),
  item('selection.field.outputVoltage', 'selection', '输出电压', '输出电压'),
  item('selection.field.outputCurrent', 'selection', '输出电流', '输出电流'),
  item('selection.field.applicationType', 'selection', '应用类型', '应用类型'),
  item('selection.field.efficiencyLevel', 'selection', '能效等级', '能效等级'),
  item('selection.field.certifications', 'selection', '认证要求', '认证要求'),
  item('selection.field.certifications.optional', 'selection', '可选认证要求', '认证要求（可选）'),
  item('selection.field.application.placeholder', 'selection', '应用类型占位文案', '选择应用类型（可选）'),
  item('selection.field.application.placeholder.short', 'selection', '应用类型短占位文案', '选择应用类型'),
  item('selection.group.electrical', 'selection', '电气参数分组', '电气参数'),
  item('selection.group.performance', 'selection', '性能参数分组', '性能参数'),
  item('selection.group.compliance', 'selection', '合规参数分组', '合规参数'),
  item('selection.application.adapter', 'selection', '应用：适配器', '适配器'),
  item('selection.application.charger', 'selection', '应用：充电器', '充电器'),
  item('selection.application.led', 'selection', '应用：LED 驱动', 'LED驱动'),
  item('selection.application.server', 'selection', '应用：服务器电源', '服务器电源'),
  item('selection.application.pfc', 'selection', '应用：PFC', 'PFC'),
  item('selection.application.industrial', 'selection', '应用：工业电源', '工业电源'),
  item('selection.efficiency.vi', 'selection', '能效：VI 级', 'VI级能效'),
  item('selection.efficiency.v', 'selection', '能效：V 级', 'V级能效'),
  item('selection.efficiency.titanium', 'selection', '能效：钛金级', '钛金级'),
  item('selection.efficiency.platinum', 'selection', '能效：白金级', '白金级'),
  item('selection.efficiency.gold', 'selection', '能效：金牌级', '金牌级'),
  item('selection.certification.ce', 'selection', '认证：CE', 'CE'),
  item('selection.certification.fcc', 'selection', '认证：FCC', 'FCC'),
  item('selection.certification.rohs', 'selection', '认证：RoHS', 'RoHS'),
  item('selection.certification.ul', 'selection', '认证：UL', 'UL'),
  item('selection.certification.ccc', 'selection', '认证：CCC', 'CCC'),
  item('selection.certification.tuv', 'selection', '认证：TUV', 'TUV'),
  item('selection.filters.title', 'selection', '筛选条件标题', '筛选条件'),
  item('selection.filters.action', 'selection', '筛选按钮', '筛选'),
  item('selection.filters.reset', 'selection', '重置条件', '重置条件'),
  item('selection.hint.title', 'selection', '精准推荐提示标题', '补充参数获取精准推荐'),
  item('selection.hint.subtitle', 'selection', '精准推荐提示说明', '当前展示热门产品，请填写输入电压、输出电压和输出电流以获取精准匹配结果。'),
  item('selection.summary.application', 'selection', '条件摘要：应用', '应用'),
  item('selection.summary.input', 'selection', '条件摘要：输入', '输入'),
  item('selection.summary.output', 'selection', '条件摘要：输出', '输出'),
  item('selection.sort.score', 'selection', '按匹配度排序', '按匹配度'),
  item('selection.sort.model', 'selection', '按型号排序', '按型号'),
  item('selection.popular.title', 'selection', '热门产品标题', '热门产品'),
  item('selection.popular.empty', 'selection', '热门产品空态', '暂无热门产品'),
  item('selection.error', 'selection', '选型查询失败', '查询失败，请重试'),
  item('selection.results.empty', 'selection', '匹配结果空态', '暂无匹配结果'),
  item('selection.results.suggestion', 'selection', '匹配建议标题', '建议调整以下参数后重试：'),
  item('selection.results.tip.input', 'selection', '匹配建议：电压', '放宽输入电压范围'),
  item('selection.results.tip.current', 'selection', '匹配建议：电流', '降低输出电流要求'),
  item('selection.results.tip.certification', 'selection', '匹配建议：认证', '减少认证筛选条件'),
  item('selection.results.tip.application', 'selection', '匹配建议：应用', '更换应用类型'),
  item('selection.results.prefix', 'selection', '匹配数量前缀', '共'),
  item('selection.results.suffix', 'selection', '匹配数量后缀', '个匹配结果'),
  item('selection.match.exact', 'selection', '精确匹配', '精确匹配'),
  item('selection.match.approximate', 'selection', '近似匹配', '近似匹配'),
  item('selection.match.fallback', 'selection', '备选方案', '备选方案'),
  item('selection.card.input', 'selection', '型号卡片：输入', '输入'),
  item('selection.card.output', 'selection', '型号卡片：输出', '输出'),
  item('selection.card.standby', 'selection', '型号卡片：待机', '待机'),
  item('selection.card.certification', 'selection', '型号卡片：认证', '认证'),
  item('selection.compare.max', 'selection', '对比最多产品提示', '最多选择3个产品进行对比'),
  item('selection.compare.title', 'selection', '产品参数对比标题', '产品参数对比'),
  item('selection.compare.item', 'selection', '对比项', '对比项'),
  item('selection.compare.score', 'selection', '匹配度', '匹配度'),
  item('selection.compare.level', 'selection', '匹配等级', '匹配等级'),
  item('selection.compare.input', 'selection', '对比输入范围', '输入范围'),
  item('selection.compare.output', 'selection', '对比输出能力', '输出能力'),
  item('selection.compare.efficiency', 'selection', '对比能效等级', '能效等级'),
  item('selection.compare.certification', 'selection', '对比认证', '认证'),
  item('selection.compare.reasons', 'selection', '对比主要理由', '主要理由'),
  item('selection.compare.diffs', 'selection', '对比差异点', '差异点'),
  item('selection.compare.noDiff', 'selection', '无明显差异', '无明显差异'),
  item('selection.compare.material', 'selection', '对比资料状态', '资料状态'),
  item('selection.compare.selected', 'selection', '已选对比', '已选对比'),
  item('selection.compare.emptySlot', 'selection', '对比空位', '空位'),
  item('selection.compare.minimum', 'selection', '最少对比产品提示', '至少选择2个产品进行对比'),
  item('selection.compare.start', 'selection', '开始对比', '开始对比'),
  item('selection.compare.add', 'selection', '加入对比', '加入对比'),
  item('selection.compare.remove', 'selection', '取消对比', '取消对比'),
  item('selection.compare.added', 'selection', '已加入对比', '已加入'),
  item('selection.compare.action', 'selection', '对比按钮', '对比'),

  item('product.kicker', 'products', '产品详情页眉', 'PRODUCT DETAIL'),
  item('product.notFound.subtitle', 'products', '产品不存在说明', '抱歉，您访问的产品不存在。'),
  item('product.loadFailed.subtitle', 'products', '产品加载失败说明', '产品信息加载失败，请稍后重试。'),
  item('product.material.preparingShort', 'products', '资料整理中短文案', '整理中'),
  item('product.solutions.empty', 'products', '关联方案空态', '暂无关联方案'),

  item('solutions.kicker', 'solutions', '方案列表页眉', 'SOLUTION LIBRARY'),
  item('solution.detail.notFound.subtitle', 'solutions', '方案不存在说明', '抱歉，您访问的方案不存在。'),
  item('solution.detail.loadFailed', 'solutions', '方案加载失败标题', '加载失败'),
  item('solution.detail.loadFailed.subtitle', 'solutions', '方案加载失败说明', '方案信息加载失败，请稍后重试。'),
  item('solution.status.active', 'solutions', '方案已发布', '已发布'),
  item('solution.status.preparing', 'solutions', '方案整理中', '整理中'),
  item('solution.preview.frameTitle', 'solutions', '预览框标题', '资料预览'),
  item('solution.preview.external.title', 'solutions', '外部预览标题', '可打开预览文件'),
  item('solution.preview.external.subtitle', 'solutions', '外部预览说明', '当前浏览器不支持直接内嵌该格式，可在新窗口中查看。'),
  item('solution.preview.external.open', 'solutions', '打开预览', '打开预览'),
  item('solution.download.selectFirst', 'solutions', '未选择资料提示', '请先选择资料'),
  item('solution.download.failed', 'solutions', '单资料下载失败', '下载失败，请稍后重试'),
  item('solution.download.loginRequired', 'solutions', '下载登录提示', '登录后可下载'),
  item('solution.download.login', 'solutions', '登录后下载按钮', '登录后下载'),
  item('solution.download.single', 'solutions', '下载资料按钮', '下载资料'),
  item('solution.download.allFailed', 'solutions', '打包下载失败', '打包下载失败，请稍后重试'),
  item('solution.download.allLoginRequired', 'solutions', '全部下载登录提示', '登录后可下载全部资料'),
  item('solution.download.allLogin', 'solutions', '登录后打包下载按钮', '登录后打包下载'),
  item('solution.download.all', 'solutions', '下载全部资料按钮', '下载全部资料'),

  item('profile.title', 'profile', '个人中心标题', '个人中心'),
  item('profile.loginRequired', 'profile', '个人中心登录提示', '请先登录'),
  item('profile.loginRequired.subtitle', 'profile', '个人中心登录说明', '登录后可查看个人中心'),
  item('profile.login', 'profile', '前往登录', '前往登录'),
  item('profile.account.title', 'profile', '账号信息标题', '账号信息'),
  item('profile.email', 'profile', '邮箱标签', '邮箱'),
  item('profile.role', 'profile', '角色标签', '角色'),
  item('profile.userId', 'profile', '用户 ID 标签', '用户ID'),
  item('profile.role.admin', 'profile', '管理员角色', '管理员'),
  item('profile.role.auditor', 'profile', '审核员角色', '审核员'),
  item('profile.role.staff', 'profile', '员工角色', '员工'),
  item('profile.role.user', 'profile', '普通用户角色', '普通用户'),
  item('profile.security.title', 'profile', '安全设置标题', '安全设置'),
  item('profile.password.title', 'profile', '登录密码标题', '登录密码'),
  item('profile.password.hint', 'profile', '密码安全说明', '建议定期修改密码以保障账号安全'),
  item('profile.password.change', 'profile', '修改密码', '修改密码'),

  item('ai.feedback.success', 'ai', '反馈成功提示', '反馈已提交'),
  item('ai.feedback.failed', 'ai', '反馈失败提示', '反馈提交失败'),
  item('ai.feedback.helpful', 'ai', '有帮助', '有帮助'),
  item('ai.feedback.unhelpful', 'ai', '无帮助', '无帮助'),
  item('ai.error.generate', 'ai', '生成失败', '生成失败'),
  item('ai.error.request', 'ai', '请求失败', '请求失败'),
  item('ai.error.retry', 'ai', '生成失败重试提示', '生成失败，请重试'),
  item('ai.stopped', 'ai', '已停止生成', '已停止生成'),
  item('ai.history.short', 'ai', '历史短标题', '历史'),
  item('ai.history.title', 'ai', '历史会话标题', '历史会话'),
  item('ai.sources.short', 'ai', '来源短标题', '来源'),
  item('ai.sources.title', 'ai', '引用来源标题', '引用来源'),
  item('ai.sources.current', 'ai', '本轮引用来源', '本轮引用来源'),
  item('ai.sources.empty', 'ai', '引用来源空态', '本次回答暂无引用来源'),
  item('ai.sources.trace', 'ai', '查看检索追踪', '查看检索追踪'),
  item('ai.sources.evidence', 'ai', '来源依据', '来源依据'),
  item('ai.input.placeholder', 'ai', '问题输入占位文案', '输入您的问题，Enter 发送，Shift+Enter 换行'),
  item('ai.input.stop', 'ai', '停止生成', '停止生成'),
  item('ai.input.send', 'ai', '发送', '发送'),
  item('ai.input.hint', 'ai', '输入快捷键说明', 'Enter 发送 · Shift+Enter 换行'),
  item('ai.empty', 'ai', '对话空态', '输入您的问题开始对话'),
  item('ai.searching', 'ai', '检索中提示', '正在检索资料...'),
  item('ai.generating', 'ai', '生成中提示', '回答生成中...'),
  item('ai.noSources', 'ai', '无相关资料提示', '暂无相关资料支持该问题'),
  item('ai.newChat', 'ai', '新建对话', '新建对话'),
  item('ai.newConversation', 'ai', '新对话标题', '新对话'),
  item('ai.recommended.title', 'ai', '推荐问题标题', '推荐问题'),
  item('ai.recommended.1', 'ai', '推荐问题 1', 'LP3798 的待机功耗是多少？'),
  item('ai.recommended.2', 'ai', '推荐问题 2', '有哪些适合充电桩的方案？'),
  item('ai.recommended.3', 'ai', '推荐问题 3', 'LP3524 的同步整流驱动特性是什么？'),
  item('ai.time.now', 'ai', '时间：刚刚', '刚刚'),
  item('ai.time.minutesAgo', 'ai', '时间：分钟前', '分钟前'),
  item('ai.time.hoursAgo', 'ai', '时间：小时前', '小时前'),
  item('ai.time.daysAgo', 'ai', '时间：天前', '天前'),
  item('ai.source.pagePrefix', 'ai', '来源页码前缀', '第'),
  item('ai.source.pageSuffix', 'ai', '来源页码后缀', '页'),
  item('ai.source.models', 'ai', '来源相关型号', '相关型号/参数'),
  item('ai.source.events', 'ai', '来源关联事项', '关联事项'),
  item('ai.source.snippet', 'ai', '来源片段', '来源片段'),
];
